import { z } from 'zod';

export const vehicleSchema = z.object({
  customer_id: z.string().uuid(),
  registration_number: z.string().min(1, 'Required'),
  make: z.string().min(1, 'Required'),
  model: z.string().min(1, 'Required'),
  variant: z.string().optional(),
  year_of_manufacture: z.coerce.number().min(1900).max(new Date().getFullYear()),
  engine_number: z.string().optional(),
  chassis_number: z.string().optional(),
  fuel_type: z.enum(['Petrol', 'Diesel', 'CNG', 'Electric', 'Hybrid']).optional(),
  color: z.string().optional(),
  seating_capacity: z.coerce.number().optional(),
  vehicle_category: z.string().min(1, 'Required'),
  vehicle_sub_type: z.string().min(1, 'Required'),
  hypothecation_details: z.string().optional(),
});

export const motorPolicySchema = z.object({
  customer_id: z.string().uuid(),
  vehicle_id: z.string().uuid(),
  policy_number: z.string().min(1, 'Required'),
  insurer_id: z.string().uuid(),
  policy_type: z.enum(['first_party', 'third_party']),
  idv: z.coerce.number().min(0).optional(),
  premium_amount: z.coerce.number().min(0),
  gst_amount: z.coerce.number().min(0),
  net_premium: z.coerce.number().min(0),
  od_premium: z.coerce.number().min(0).optional(),
  tp_premium: z.coerce.number().min(0),
  od_start_date: z.string().optional(),
  od_expiry_date: z.string().optional(),
  tp_start_date: z.string().min(1, 'Required'),
  tp_expiry_date: z.string().min(1, 'Required'),
  standalone_od_flag: z.boolean().default(false),
  linked_tp_policy_id: z.string().uuid().optional(),
  start_date: z.string().optional(),
  expiry_date: z.string().optional(),
  ncb_percent: z.coerce.number().optional().default(0),
  ncb_protect: z.boolean().default(false),
  addons: z.array(z.string()).optional(),
  policy_file_key: z.string().optional(),
});
